### PR TITLE
Use triple double-quoted strings for docstring (PEP8), fix typo

### PR DESCRIPTION
**Pull request by delirious-lettuce**
### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- [Use triple double-quoted strings for docstring (PEP8)](http://pep8.org/#documentation-strings)
- Fix typos:
    * `erro` -> `error`
    * `successsful` -> `successful`

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/python-http-client?pullRequest=71) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/python-http-client?pullRequest=71) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/python-http-client?pullRequest=71) it.</sub>

**Comment by thinkingserious** [comment]
@delirious-lettuce

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by mbernier** [comment]
@delirious-lettuce 

If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by thinkingserious** [comment]
Hi @delirious-lettuce,

This has come up to the top of my backlog to merge. Could you please fix the merge conflict so that I may merge this PR?

Thanks!

With Best Regards,

Elmer

**Comment by delirious-lettuce** [comment]
@thinkingserious ,

I actually deleted my fork a while ago since I thought this PR was abandoned. I could fork and re-submit a new PR that does the exact same thing but otherwise I'm not sure how to proceed?

**Comment by thinkingserious** [comment]
A new PR would work, thanks!

**Comment by delirious-lettuce** [comment]
@thinkingserious ,

Ok, sorry about the mixup! I'll re-submit ASAP.

**Comment by thinkingserious** [comment]
No worries @delirious-lettuce :)

We are running very behind due to a wonderful Hacktoberfest turn out.

**Comment by delirious-lettuce** [comment]
@thinkingserious ,

No problem at all, I can only imagine how hard it would be to go through hundreds (if not thousands!) of pull requests!

**Pull request closed without merging**
