### PR TITLE
Update travis.yml to fail on Pep8 errors

### LINKED ISSUE #63: Add a PEP8 check to travis.yml
#### Issue Summary

According to codeClimate, this repo is not conforming with PEP8 standards. Please add a PEP8 check to Travis that will cause the build to fail if the proper rules are not being met. 

#### Steps to Reproduce

1. Install the check
2. Make obvious PEP8 standards violation in one of the files
3. Make a PR
4. Let the build run
5. See a failure in the build
6. Fix the issue and make a comment (so we know)
7. Get a free Hacktoberfest shirt (so long as your first PR is in Oct)

### PR DESCRIPTION
**Pull request by NdagiStanley**
**Description of the change**:
Update travis.yml to fail on Pep8 errors

**Reason for the change**:
Fixes #63

### CODE REVIEW

**Comment by mbernier** [comment]
@NdagiStanley

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by NdagiStanley** [comment]
I have filled out the form. Could you tell me why the PR couldn't be merged? I still want to finish this :)

**Comment by thinkingserious** [comment]
Hi @NdagiStanley,

Your PR has not been merged simply because we are way behind :( There were over 1,000 PRs submitted to us in October and we are currently merging them from oldest to newest while also trying to make sure you all get your swag.

We appreciate your contribution and patience.

With Best Regards,

Elmer

**Comment by mbernier** [comment]
I merged the conflicts and we're now waiting for Travis to build - 


in the meantime ... 


If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@sendgrid-ci

**Comment by thinkingserious** [comment]
Hello @NdagiStanley,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
