### PR TITLE
Allow multiple values for a parameter

### PR DESCRIPTION
**Pull request by chrishenry**
This is a fix for https://github.com/sendgrid/sendgrid-python/issues/186

### CODE REVIEW

**Comment by thinkingserious** [comment]
This is awesome @chrishenry!

Could you please sign our CLA so we can merge? https://github.com/sendgrid/python-http-client/blob/master/CONTRIBUTING.md#cla

Thanks!

**Comment by chrishenry** [comment]
Thanks! I'm away for a few days, but look for the CLA by late next week.

**Comment by thinkingserious** [comment]
@chrishenry just checking on the CLA status. This fix is next on our list. Thanks!

**Comment by chrishenry** [comment]
Hi @thinkingserious! Sorry for the delay, I've just emailed the CLA in.

**Comment by thinkingserious** [comment]
Please shoot us another email with your T-shirt size and mailing address so we can send you some swag :)

**Pull request merged**
