### PR TITLE
Add manifest that includes the license in sdist

### PR DESCRIPTION
**Pull request by RohitK89**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds a manifest so that the license file exists in the Pypi tar ball

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thanks @RohitK89,

This is now on our backlog for review and merge.

**Comment by thinkingserious** [comment]
Hello @RohitK89,

Thanks again for taking the time to make a PR.

Why do you think we need a Manifest.in file? According to [this thread](https://stackoverflow.com/questions/24727709/do-python-projects-need-a-manifest-in-and-what-should-be-in-it), it seems like it's not needed.

With Best Regards,

Elmer

**Comment by RohitK89** [comment]
I added sendgrid as a package on conda-forge (
https://anaconda.org/conda-forge/sendgrid), and the lack of a manifest
meant that I had to explicitly specify the license. It's not necessary
strictly, but it makes it easier for the package to be maintained elsewhere.

**Comment by thinkingserious** [comment]
Sounds good, thanks!

**Comment by thinkingserious** [comment]
Hello @RohitK89,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
