### PR TITLE
converted README and version as file

### PR DESCRIPTION
**Pull request by StrikerRUS**
### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [n/a] I have added necessary documentation about the functionality in the appropriate .md file
- [n/a] I have added in line documentation to the code I modified

### Short description of what this PR does:
- add standard `__version__` attribute to the package. This attribute is read from the `VERSION.txt` file, so in the future version should be incremented only in the file (related to #92).
- convert `README.md` to `README.rst` (appearance can be checked in this branch https://github.com/StrikerRUS/python-http-client/blob/pypi/README.rst), so `setup.cfg` and `register.py` are not needed anymore.
- add Python versions badge.
   
- add PyPI version badge.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/python-http-client?pullRequest=93) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/python-http-client?pullRequest=93) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/python-http-client?pullRequest=93) it.</sub>

**Comment by StrikerRUS** [comment]
All tests on Travis are green, but the status on GitHub hasn't been updated. If it's an issue, then closing and reopening the PR can help.

**Comment by thinkingserious** [comment]
Hello @StrikerRUS,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
This is awesome @StrikerRUS! Would you mind doing the same for our other Python repos?

https://github.com/sendgrid/sendgrid-python
https://github.com/sendgrid/smtpapi-python
https://github.com/sendgrid/open-source-library-data-collector
https://github.com/sendgrid/dx-automator

Thanks!

With Best Regards,

Elmer

**Comment by StrikerRUS** [comment]
@thinkingserious Thanks a lot for the kind words!

Sure, I'll create PRs for other repos.
BTW, the similar PR for `sendgrid-python` has been already created: https://github.com/sendgrid/sendgrid-python/pull/634.

**Comment by StrikerRUS** [comment]
@thinkingserious Here're updates about PRs. Please take a look.

- sendgrid/sendgrid-python: ~https://github.com/sendgrid/sendgrid-python/pull/634~ https://github.com/sendgrid/sendgrid-python/pull/663.
- sendgrid/smtpapi-python: https://github.com/sendgrid/smtpapi-python/pull/75.
- sendgrid/open-source-library-data-collector: https://github.com/sendgrid/open-source-library-data-collector/pull/138.
- sendgrid/dx-automator: Not needed.

**Pull request merged**
